### ISSUE TITLE
AUR, GURU, COPR etc.

### ISSUE THREAD

**Issue by WavyEbuilder** [ArtixLabs/Niagara#5]
I was wondering how we could handle things like hyprland or gui-apps/rofi-wayland which are both not in offical repos. These are just examples, but maybe we could have a flag like "non-official: true" in the .yml file that allows for these repos to be added to a user's configuration? Then we could add a packages-non-official.py file with those sorts of packages for seperation.

**Comment by Cobalt-Inferno** [comment]
I'm actually currently in the process of making a rust rewrite of Niagara.  I did not correctly plan out the current version, so it has a very messy codebase. Once I finish the base version of it (Installing native packages,) I will expand into things like this.

**Comment by WavyEbuilder** [comment]
I will try and contribute the best I can with rust, but unfortunately I am not very familar, but I am learning the fundermentals atm, so we will see :)

**Comment by Cobalt-Inferno** [comment]
I have fully decided to abandon the rewrite & this repository, as I am now focusing on my new project written in Haskell.  I apologize for never updating you about this.

**Comment by WavyEbuilder** [comment]
No problem! Good luck with that
